# Generated by Django 4.2.5 on 2023-09-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0002_investmento_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmento',
            name='nivel',
        ),
    ]
